In [1]:
# Homework 10: Astropy

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from astropy import units as u
from astropy import constants as const

In [22]:
df = pd.read_csv('solar_system.csv')
df.shape

(20, 11)

In [23]:
df = df.set_index("Attribute").T
df.shape
# Makes the 'attribute' the header (flips the table)

(10, 20)

In [24]:
df.index.name = "Planet"
df.shape
# Rows have now become planets, so they need to be named accordingly

(10, 20)

In [25]:
df.reset_index(inplace=True)
df.shape
# Moves planet from being an index to a regular column

(10, 21)

In [26]:
df.columns.name = None
df.shape
# Clears the name 'attribute' from the column'

(10, 21)

In [27]:
# Before: 20 rows, 11 co;lumns
# After: 10 rows, 21 columns

In [28]:
# Using set_index and reset_index removes a column and then adds it back as an index; 
#print(df.columns)    'attribute' became the headers and Planets became the rows.

In [29]:
print(df.columns)

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [30]:
# Units: Diameter, density, gravity, esc velocity, rotation period, length of day, distance from sun, perihelion, 
    # aphelion, oprbital period, orbital velocity, orbital inclination, obliquity to orbit, mean temperature, surface pressure
# No units: Orbital eccentricity, number of moons, ring system?, global magnetic field?, planet

In [31]:
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [32]:
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [33]:
df[col].apply(type)
# Strings
# Hard to do numerical analysis/calculations with

NameError: name 'col' is not defined

In [34]:
cols_to_skip = ["Planet", "Ring System?", "Global Magnetic Field?"]
for col in df.columns:
    if col not in cols_to_skip:
        df[col] = pd.to_numeric(df[col], errors='coerce')
df.dtypes

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

In [35]:
# float64: decimal numbers
# int64: whole integers
# object: text strings (i.e. y/n)

# planet, ring system?, and global magnetic field where excluded since their data needs to be a string (planet name or y/n)

In [36]:
import astropy.units as u

def attach_units(col_name, unit, new_name):
    if col_name in df.columns:
        new_values = []
        
        for val in df[col_name]:
            new_values.append(val * unit)
            
        df[col_name] = new_values
        
        df.rename(columns={col_name: new_name}, inplace=True)

attach_units("Mass (10^24kg)", 1e24 * u.kg, "Mass (kg)")

attach_units("Diameter (km)", u.km, "Diameter (km)")

attach_units("Density (kg/m3)", u.kg / u.m**3, "Density (kg/m^3)")

attach_units("Gravity (m/s2)", u.m / u.s**2, "Gravity (m/s^2)")

attach_units("Escape Velocity (km/s)", u.km / u.s, "Escape Velocity (km/s)")

attach_units("Rotation Period (hours)", u.hour, "Rotation Period (hours)")

attach_units("Length of Day (hours)", u.hour, "Length of Day (hours)")

attach_units("Distance from Sun (10^6 km)", 1e6 * u.km, "Distance from Sun (km)")

attach_units("Perihelion (10^6 km)", 1e6 * u.km, "Perihelion (km)")

attach_units("Aphelion (10^6 km)", 1e6 * u.km, "Aphelion (km)")

attach_units("Orbital Period (days)", u.day, "Orbital Period (days)")

attach_units("Orbital Velocity (km/s)", u.km / u.s, "Orbital Velocity (km/s)")

attach_units("Orbital Inclination (degrees)", u.deg, "Orbital Inclination (degrees)")

attach_units("Obliquity to Orbit (degrees)", u.deg, "Obliquity to Orbit (degrees)")

attach_units("Mean Temperature (C)", u.deg_C, "Mean Temperature (C)")

attach_units("Surface Pressure (bars)", u.bar, "Surface Pressure (bars)")

df.head(1)

,Planet,Mass (kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,3.3e+23 kg,4879.0 km,5429,3.7,4.3 km / s,1407.6 h,4222.6 h,57900000.0 km,46000000.0 km,...,88.0 d,47.4 km / s,7.0,0.206,0.034,167.0 deg_C,0.0 bar,0,No,Yes

In [37]:
semi_major_axis = (df["Perihelion (km)"] + df["Aphelion (km)"]) / 2

loc_index = df.columns.get_loc("Aphelion (km)") + 1

df.insert(loc_index, "Semi-Major Axis (km)", semi_major_axis)

print(df.columns.tolist())

['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (km)', 'Perihelion (km)', 'Aphelion (km)', 'Semi-Major Axis (km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

In [38]:
df["Semi-Major Axis (km)"]

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384500.0 km
4     228000000.0 km
5     778500000.0 km
6    1432050000.0 km
7    2867050000.0 km
8    4515000000.0 km
9    5906350000.0 km
Name: Semi-Major Axis (km), dtype: object

In [39]:
df['Orbital Period (days)'] = df['Orbital Period (days)'].apply(lambda x: x.to(u.yr))

df.rename(columns={'Orbital Period (days)': 'Orbital Period (years)'}, inplace=True)

print("Updated Columns:", df.columns)

print(df['Orbital Period (years)'])

fave_planet = df.loc[df['Planet'] == 'Saturn'].iloc[0]
print(f"\nSaturn's Orbital Period: {fave_planet['Orbital Period (years)'].value:.4f} years")

Updated Columns: Index(['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (km)', 'Perihelion (km)',
       'Aphelion (km)', 'Semi-Major Axis (km)', 'Orbital Period (years)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')
0    0.24093086926762491 yr
1     0.6151950718685831 yr
2     0.9998631074606433 yr
3    0.07474332648870637 yr
4     1.8809034907597535 yr
5      11.85763175906913 yr
6     29.423682409308693 yr
7      83.74811772758385 yr
8     163.72347707049965 yr
9     247.93976728268308 yr
Name: Orbital Period (years), dtype: object

Saturn's Orbital Period: 29.4237 years

In [42]:
print(f"1 AU in Astropy: {const.au}")

km_in_au = const.au.to(u.km)
print(f"Kilometers in 1 AU: {km_in_au}")

cols_to_convert = [col for col in df.columns if '(km)' in col]

print(f"\nConverting the following columns to AU: {cols_to_convert}")

for col in cols_to_convert:
    df[col] = df[col].apply(lambda x: x.to(u.AU))
    
    new_col_name = col.replace('(km)', '(AU)')
    
    df.rename(columns={col: new_col_name}, inplace=True)

saturn_row = df[df['Planet'] == 'Saturn'].iloc[0]

for col in df.columns:
    if '(AU)' in col:
        print(f"{col}: {saturn_row[col]}")

1 AU in Astropy: 149597870700.0 m
Kilometers in 1 AU: 149597870.70000002 km

Converting the following columns to AU: []
Diameter (AU): 0.0008057333933697493 AU
Distance from Sun (AU): 9.572328759088414 AU
Perihelion (AU): 9.074995477191642 AU
Aphelion (AU): 10.070330499697413 AU
Semi-Major Axis (AU): 9.572662988444527 AU

In [43]:
df.to_csv("units.csv", index=False)